### ISSUE TITLE
Package '7za' at version '16.02.2' is missing from local storage.

### ISSUE THREAD

**Issue by Yousazoe** [NVIDIAGameWorks/Falcor#285]
I tried to use [cwyman's tutorial](http://cwyman.org/code/dxrTutors.Code.zip) to reproduce, which used Falcor, and the following error was reported when running in VisualStudio2022：
```
已启动生成…
1>------ 已启动生成: 项目: Tutor01-OpenWindow, 配置: Debug x64 ------
1>Package '7za' at version '16.02.2' is missing from local storage.
1>Traceback (most recent call last):
1>  File "E:\packman-repo\packman-common\5.3.1\packman.py", line 1012, in <module>
1>    main()
1>  File "E:\packman-repo\packman-common\5.3.1\packman.py", line 993, in main
1>    return args.func(**vars(args))
1>  File "E:\packman-repo\packman-common\5.3.1\packman.py", line 196, in install
1>    pull_dependencies(dep_map, remote_configs, remote_names, None, postscript=postscript, variable_file=variable_file)
1>  File "E:\packman-repo\packman-common\5.3.1\packman.py", line 578, in pull_dependencies
1>    target_filename = os.path.join(temp_dir, package_filename)
1>  File "E:\packman-repo\python\2.7.14-windows-x86_32\lib\ntpath.py", line 85, in join
1>    result_path = result_path + p_path
1>UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 7: ordinal not in range(128)
1>!!! Failure while configuring local machine :( !!!
1>E:\Dev\IDE\VisualStudio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: 命令“call E:\Dev\dxrCode\\Falcor\Framework\\BuildScripts\prebuild.bat E:\Dev\dxrCode\\Falcor\Framework\ E:\Dev\dxrCode\ E:\Dev\dxrCode\01-OpenWindow\ x64 x64 Debug E:\Dev\dxrCode\Bin\x64\Debug\
1>E:\Dev\IDE\VisualStudio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: :VCEnd”已退出，代码为 1。
1>已完成生成项目“01-OpenWindow.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========
```
How can I install this dependency?

**Comment by skallweitNV** [comment]
This seems to be a very old version of Falcor. You might try upgrading packman to a newer version.
